controller_manager:
  ros__parameters:
    update_rate: 100  # Hz
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
    ackermann_steering_controller:
      type: 'ackermann_steering_controller/AckermannSteeringController'

ackermann_steering_controller:
  ros__parameters:
    wheelbase: 0.315
    front_wheel_track: 0.1856
    rear_wheel_track: 0.1856
    front_wheels_radius: 0.054
    rear_wheels_radius: 0.054
    front_steering: true
    reference_timeout: 9999.0
    rear_wheels_names: ['rear_right_wheel_joint', 'rear_left_wheel_joint']
    front_wheels_names: ['front_right_steering_joint', 'front_left_steering_joint']
    use_stamped_vel: false
    open_loop: false
    velocity_rolling_window_size: 10
    base_frame_id: base_footprint
    odom_frame_id: odom
    enable_odom_tf: false
    twist_covariance_diagonal: [0.0, 7.0, 14.0, 21.0, 28.0, 35.0]
    pose_covariance_diagonal: [0.0, 7.0, 14.0, 21.0, 28.0, 35.0]
    position_feedback: true
